/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (https://www.swig.org).
 * Version 4.4.1
 *
 * Do not make changes to this file unless you know what you are doing - modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package org.libtorrent4j.swig;

public class disk_io_file_provider {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  protected disk_io_file_provider(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(disk_io_file_provider obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected static long swigRelease(disk_io_file_provider obj) {
    long ptr = 0;
    if (obj != null) {
      if (!obj.swigCMemOwn)
        throw new RuntimeException("Cannot release ownership as memory is not owned");
      ptr = obj.swigCPtr;
      obj.swigCMemOwn = false;
      obj.delete();
    }
    return ptr;
  }

  @SuppressWarnings({"deprecation", "removal"})
  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        libtorrent_jni.delete_disk_io_file_provider(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  protected void swigDirectorDisconnect() {
    swigCMemOwn = false;
    delete();
  }

  public void swigReleaseOwnership() {
    swigCMemOwn = false;
    libtorrent_jni.disk_io_file_provider_change_ownership(this, swigCPtr, false);
  }

  public void swigTakeOwnership() {
    swigCMemOwn = true;
    libtorrent_jni.disk_io_file_provider_change_ownership(this, swigCPtr, true);
  }

  public int open_file(String info_hash, int file_index, String relative_path, String save_path) {
    return (getClass() == disk_io_file_provider.class) ? libtorrent_jni.disk_io_file_provider_open_file(swigCPtr, this, info_hash, file_index, relative_path, save_path) : libtorrent_jni.disk_io_file_provider_open_fileSwigExplicitdisk_io_file_provider(swigCPtr, this, info_hash, file_index, relative_path, save_path);
  }

  public void release_file(String info_hash, int file_index, int fd, String relative_path, String save_path) {
    if (getClass() == disk_io_file_provider.class) libtorrent_jni.disk_io_file_provider_release_file(swigCPtr, this, info_hash, file_index, fd, relative_path, save_path); else libtorrent_jni.disk_io_file_provider_release_fileSwigExplicitdisk_io_file_provider(swigCPtr, this, info_hash, file_index, fd, relative_path, save_path);
  }

  public boolean delete_file(String info_hash, int file_index, String relative_path, String save_path) {
    return (getClass() == disk_io_file_provider.class) ? libtorrent_jni.disk_io_file_provider_delete_file(swigCPtr, this, info_hash, file_index, relative_path, save_path) : libtorrent_jni.disk_io_file_provider_delete_fileSwigExplicitdisk_io_file_provider(swigCPtr, this, info_hash, file_index, relative_path, save_path);
  }

  public boolean rename_file(String info_hash, int file_index, String relative_path, String save_path, String new_name) {
    return (getClass() == disk_io_file_provider.class) ? libtorrent_jni.disk_io_file_provider_rename_file(swigCPtr, this, info_hash, file_index, relative_path, save_path, new_name) : libtorrent_jni.disk_io_file_provider_rename_fileSwigExplicitdisk_io_file_provider(swigCPtr, this, info_hash, file_index, relative_path, save_path, new_name);
  }

  public boolean move_storage(String info_hash, String old_save_path, String new_save_path) {
    return (getClass() == disk_io_file_provider.class) ? libtorrent_jni.disk_io_file_provider_move_storage(swigCPtr, this, info_hash, old_save_path, new_save_path) : libtorrent_jni.disk_io_file_provider_move_storageSwigExplicitdisk_io_file_provider(swigCPtr, this, info_hash, old_save_path, new_save_path);
  }

  @SuppressWarnings("this-escape")
  public disk_io_file_provider() {
    this(libtorrent_jni.new_disk_io_file_provider(), true);
    libtorrent_jni.disk_io_file_provider_director_connect(this, swigCPtr, true, true);
  }

}
